### ISSUE TITLE
3D модель промышленного объекта РСФСР

### ISSUE THREAD

**Issue by ArgentumAuri** [ArgentumAuri/Intensive1Team#13]
Результат: .blend файл c моделью промышленного объекта.

Требования:

- [x] Стилистика LowPoly

- [x] Модель самостоятельная

- [x] Модель окрашена

- [x] Модель узнаваемая

**Comment by Skarovich** [comment]
[РСФСР.zip](https://github.com/ArgentumAuri/Intensive1Team/files/10087411/default.zip)
Нижнекамскнефтехим
Череповецкий металлургический завод

**Comment by ArgentumAuri** [comment]
Задача выполнена!
