### ISSUE TITLE
3D модель промышленного объекта Таджикской ССР

### ISSUE THREAD

**Issue by ArgentumAuri** [ArgentumAuri/Intensive1Team#14]
Результат: .blend файл c моделью промышленного объекта.

Требования:

- [x] Стилистика LowPoly

- [x] Модель самостоятельная

- [x] Модель окрашена

- [x] Модель узнаваемая

**Comment by Skarovich** [comment]
[Таджикская ССР.zip](https://github.com/ArgentumAuri/Intensive1Team/files/10086986/default.zip)
Таджикский Алюминиевый Завод
Яванская ТЭЦ

**Comment by ArgentumAuri** [comment]
Задача выполнена.
