### ISSUE TITLE
3D модель промышленного объекта Туркменской ССР

### ISSUE THREAD

**Issue by ArgentumAuri** [ArgentumAuri/Intensive1Team#15]
Результат: .blend файл c моделью промышленного объекта.

Требования:

- [x] Стилистика LowPoly

- [x] Модель самостоятельная

- [x] Модель окрашена

- [x] Модель узнаваемая

**Comment by shilovavar** [comment]
[Turkmenistan.zip](https://github.com/ArgentumAuri/Intensive1Team/files/10086236/Turkmenistan.zip)
intensive_glassFactory - Ашхабадский стекольный комбинат
intensive_gres - Марыйская ГРЭС

**Comment by ArgentumAuri** [comment]
Задача выполнена!
