### ISSUE TITLE
3D модель промышленного объекта Узбекской ССР

### ISSUE THREAD

**Issue by ArgentumAuri** [ArgentumAuri/Intensive1Team#16]
Результат: .blend файл c моделью промышленного объекта.

Требования:

- [x] Стилистика LowPoly

- [x] Модель самостоятельная

- [x] Модель окрашена

- [x] Модель узнаваемая

**Comment by shilovavar** [comment]
[Uzbekistan.zip](https://github.com/ArgentumAuri/Intensive1Team/files/10086195/Uzbekistan.zip)
intensive_1 - Сырдарьинская ТЭС
intensive_tes - Ангренская ТЭС

**Comment by shilovavar** [comment]
[intensive_1.zip](https://github.com/ArgentumAuri/Intensive1Team/files/10086433/intensive_1.zip)
Перевернуты нормали

**Comment by ArgentumAuri** [comment]
Задача выполнена!
